FROM ghcr.io/lavalink-devs/lavalink:4
USER root
RUN apt-get update && apt-get install -y software-properties-common curl && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp
USER lavalink
WORKDIR /opt/Lavalink
COPY application.yml /opt/Lavalink/application.yml