version: '3.8'
services:
  lavalink:
    build:
      context: .
      dockerfile: Dockerfile.lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
      - YOUTUBE_PO_TOKEN=${YOUTUBE_PO_TOKEN}
      - YOUTUBE_VISITOR_DATA=${YOUTUBE_VISITOR_DATA}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --header=\"Authorization: youshallnotpass\" --spider http://127.0.0.1:2333/version || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - musicbots
  bots:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bots
    restart: always
    depends_on:
      lavalink:
        condition: service_healthy

    networks:
      - musicbots

networks:
  musicbots:
    driver: bridge
volumes:
  redis_data:
