version: '3.8'
services:
  lavalink:
    build:
      context: .
      dockerfile: Dockerfile.lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
      - YOUTUBE_PO_TOKEN=${YOUTUBE_PO_TOKEN}
      - YOUTUBE_VISITOR_DATA=${YOUTUBE_VISITOR_DATA}
      - IPV6_BLOCK=${IPV6_BLOCK}
      - YOUTUBE_HTTP_PROXY=${YOUTUBE_HTTP_PROXY}
      - YOUTUBE_PROXY_URL=${YOUTUBE_PROXY_URL}
      - YOUTUBE_PROXY_USERNAME=${YOUTUBE_PROXY_USERNAME}
      - YOUTUBE_PROXY_PASSWORD=${YOUTUBE_PROXY_PASSWORD}
      - YOUTUBE_OAUTH_TOKEN=${YOUTUBE_OAUTH_TOKEN}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --header=\"Authorization: youshallnotpass\" --spider http://127.0.0.1:2333/version || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - musicbots

  yt-cipher:
    image: ghcr.io/kikkia/yt-cipher:master
    container_name: yt-cipher
    restart: unless-stopped
    environment:
      - API_TOKEN=youshallnotpass
    networks:
      - musicbots
    ports:
      - "8001:8001"

  bots:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bots
    restart: always
    env_file:
      - .env
    depends_on:
      lavalink:
        condition: service_healthy

    networks:
      - musicbots

networks:
  musicbots:
    driver: bridge
volumes:
  redis_data:
